
version: '3.8'
services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    depends_on:
      - mongo-seed
  mongo-seed:
    image: mongo:latest
    volumes:
      - C:\Users\35193\Documents\GitHub\-ENGWEB2024--Normal--A100711\contratos2024.json:/datasets/dataset.json
    command: mongoimport --host mongodb -d contratos -c contratos --type json --file /datasets/dataset.json --jsonArray
